zuul:
  routes:
  # /myProduct/product/list -> /product/product/list
    aaaaaa:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
  #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
  #所有服务都可使用cookie
  sensitive-headers:   
management:
  security:
    enabled: false
spring:
  redis:
    host: localhost
    port: 6379         